19 하단 nav 바
prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE pull request #25
Opened 2023-10-26 09:35 UTC by Jeong-Taeho

## 구현 내용
- 하단 nav바를 구현했습니다.
- 아이콘 텍스트가 묶여있는 부분이 많이 쓰이는 것 같아 `IconGroup` 컴포넌트를 구현했습니다.
- route props가 존재하면 이동하고 없으면 그냥 아이콘처럼 쓰이도록 구현했습니다.
## 스크린샷
![image](https://github.com/prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE/assets/117630589/384bc9aa-a649-4a68-8521-56799b690ad4)

## 궁금한 점
이렇게 해도 괜찮을 지 모르겠네요..!

## 이슈번호
- closes #19

2023-10-26 09:40 UTC, Howon-Shin approved these changes
확인했습니다!

2023-10-26 15:06 UTC, jkea1 requested changes
굳굳! 확인했습니다. 파이팅!

2023-10-26 15:06 UTC, jkea1 commented on one-day-hero/src/components/common/BottomNav.tsx
> +    <div className="bg-stone-200 flex justify-center items-center w-96 h-14 gap-10 shadow-[0px_-2px_5px_rgba(0,0,0,0.07)]">
div 대신 nav 나 다른 시멘틱 태그를 사용해 보시는 건 어떨까요??

2023-10-26 15:06 UTC, jkea1 commented on one-day-hero/src/components/common/IconGroup.tsx
> +const IconGroup = ({
Icon이 하나 들어가는 것 같은데 Icon 이라는 이름이 더 맞을 것 같습니다.

2023-10-26 15:06 UTC, jkea1 commented on one-day-hero/src/components/common/IconGroup.tsx
> +}: PropsWithChildren<{ title: string; route?: string }>) => {
`{ title: string; route?: string }` 이 부분은 일관성을 위해서  IconProps 으로 따로 빼주는 건 어떨까요??

2023-10-26 16:09 UTC, Jeong-Taeho commented on one-day-hero/src/components/common/BottomNav.tsx
> +    <div className="bg-stone-200 flex justify-center items-center w-96 h-14 gap-10 shadow-[0px_-2px_5px_rgba(0,0,0,0.07)]">
넵!!

2023-10-26 16:09 UTC, Jeong-Taeho commented on one-day-hero/src/components/common/BottomNav.tsx
> +      <IconGroup title="홈" route="/">
<Link>도 use client를 사용해야 된다 생각하고 제일 하단에서 처리해야겠다하고 router로 했는데 제가 완전 잘못 알고 있었나봐요... 고쳐서 다시 올리겠습니다😊

2023-10-26 16:09 UTC, Jeong-Taeho commented on one-day-hero/src/components/common/IconGroup.tsx
> +const IconGroup = ({
Icon + text라서 Group이라고 했는데 보기좋게 Icon으로 수정할까요??

2023-10-26 16:09 UTC, Jeong-Taeho commented on one-day-hero/src/components/common/IconGroup.tsx
> +}: PropsWithChildren<{ title: string; route?: string }>) => {
넵!!

2023-10-27 05:37 UTC, jkea1 commented on one-day-hero/src/components/common/IconGroup.tsx
> +const IconGroup = ({
제가 Icon만 있는 걸로 착각했네요! 그대로 하셔도 괜찮을 것 같습니다!

2023-10-27 05:39 UTC, jkea1 approved these changes
확인했습니다! 굿굿!

2023-10-27 05:45 UTC, merged