미션 목록 페이지 (진행중인 미션) 생성
prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE pull request #72
Opened 2023-11-01 15:10 UTC by jkea1

## 구현 내용
* 미션 목록 페이지(진행중인 미션)를 생성했습니다. 
* footer 의 미션 부분의 주소를 수정했습니다. 
* 텝 컴포넌트 수정했습니다. 
  * rightText, leftText 속성에 해당 텍스트 전달 시 텍스트 문자가 보여지고 링크를 이용하여 주소가 바뀌게 만들었습니다. 
  * `<Tabs leftText="진행중인 미션" rightText="제안받은 미션" />`
  * 미션 상세 정보 부분이 줄바꿈이 되네요. mock 데이터 받으면 padding 조절해서 다시 스타일 수정해 볼게요.

* MissionProgressContainter 컴포넌트 생성했습니다. 
![Screenshot 2023-11-02 at 12 00 15 AM](https://github.com/prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE/assets/99384699/5c238110-014f-4925-8b11-acdd3e232146)

## 스크린샷
- 테블릿 사이즈
 <img src="https://github.com/prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE/assets/99384699/9c11b9c3-6926-4677-9c2f-6ec70a805701" width="200" />

- 모바일 사이즈

https://github.com/prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE/assets/99384699/ea471523-f70c-406f-b1e5-0c9ab4cdfebf

## 궁금한 점
tabs 컴포넌트 부분부터는 미션 카드들이 탭 아래로 들어가야 하는데 보여버리네요. 좋은 아이디어 있으시면 공유해 주세요.  

## 2023.11.2 수 업데이트
위의 문제를 z-index를 이용해서 우선 해결했습니다. 

https://github.com/prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE/assets/99384699/4521276c-ba1b-4683-81e7-429bbc68c3ce

## 이슈번호
- closes #69

2023-11-02 05:26 UTC, Jeong-Taeho approved these changes
고생하셨습니다!! 저것만 해결되면 깔끔하네요😊

2023-11-02 05:26 UTC, Jeong-Taeho commented on one-day-hero/src/app/mission/list/layout.tsx
> +flex w-full max-w-screen-sm justify-center">
margin bottom으로 조절해서 하는 방법은 너무 그런가요..? 🥲

2023-11-02 05:42 UTC, Howon-Shin requested changes
확인했습니다~

2023-11-02 05:42 UTC, Howon-Shin commented on one-day-hero/src/components/common/MissionProgressContainer.tsx
> +    </Container>
MissionProgressBar에 missionState를 내려주기 위한 Prop도 필요할 것 같아요!

2023-11-02 05:42 UTC, Howon-Shin commented on one-day-hero/src/components/common/MissionProgressContainer.tsx
> +    <Container className="cs:w-10/12 px-0 pb-0">
`cs:w-10/12 cs:px-0 cs:pb-0`처럼 다 붙여줘야 우선순위를 모두 받을 수 있을 것 같아요!

2023-11-02 05:42 UTC, Howon-Shin commented on one-day-hero/src/components/common/Tabs.tsx
> +    "cs:mx-1 flex h-10 w-24 flex-auto items-center justify-center rounded-full";
`mx-1` 에 `cs:` 지정하신 이유가 있으신가요?

2023-11-02 05:42 UTC, Howon-Shin commented on one-day-hero/src/components/common/Tabs.tsx
> +  const rightRoute = route[rightText] || "/";
이걸 prop으로 받아오는 것도 좋을 것 같아요!

2023-11-02 05:42 UTC, Howon-Shin commented on one-day-hero/src/app/mission/list/layout.tsx
> +      </div>
👍

2023-11-02 07:14 UTC, jkea1 commented on one-day-hero/src/components/common/MissionProgressContainer.tsx
> +    </Container>
그러네요! 수정하겠습니다!

2023-11-02 07:20 UTC, jkea1 commented on one-day-hero/src/components/common/Tabs.tsx
> +  const rightRoute = route[rightText] || "/";
좀 더 설명 부탁드려도 괜찮을까요?

2023-11-02 07:21 UTC, jkea1 commented on one-day-hero/src/app/mission/list/layout.tsx
> +flex w-full max-w-screen-sm justify-center">
한번 다시 해보겠습니다! 감사합니다!

2023-11-02 07:24 UTC, jkea1 commented on one-day-hero/src/components/common/Tabs.tsx
> +    "cs:mx-1 flex h-10 w-24 flex-auto items-center justify-center rounded-full";
연습하다가 넣은 건데 지우는걸 잊었네요! 수정하겠습니다!

2023-11-02 07:30 UTC, Howon-Shin commented on one-day-hero/src/components/common/Tabs.tsx
> +  const rightRoute = route[rightText] || "/";
지금 `Tabs`가 `leftText`랑 `rightText`를 prop으로 받아오고 있는데 `leftRoute`, `rightRoute`도 prop에서 받아오면 확장성이 더 좋을 것 같습니다!

2023-11-02 08:06 UTC, jkea1 commented on one-day-hero/src/components/common/Tabs.tsx
> +  const rightRoute = route[rightText] || "/";
상위에서 받아오는 걸 이것 저것 해봤는데요. 지금으로서는 leftRoute가 leftText랑 종속성이 있어서 Tabs 컴포넌트 내부에서 처리하는 것 밖에 생각을 못하겠어요... 🥹😂 혹시 리팩토링 하게 된다면 같이 해봅시다!

2023-11-03 04:47 UTC, Howon-Shin approved these changes

2023-11-03 05:31 UTC, merged